## media.plex.values.yml

claimToken: "claim-TS5Vgqk-dm1uuxRGKdTm"

image:
  repository: linuxserver/plex
  tag: arm32v7-latest
  pullPolicy: IfNotPresent

kubePlex:
  enabled: false # kubePlex (transcoder job) is disabled because not available on ARM. The transcoding will be performed by the main Plex instance instead of a separate Job.

timezone: US/Eastern

service:
  type: LoadBalancer # We will use a LoadBalancer to obtain a virtual IP that can be exposed to Plex Media via our router
  port: 32400 # Port to expose Plex

rbac:
  create: true

nodeSelector: {}

persistence:
  transcode:
    claimName: "plex-pvc"
  data:
    claimName: "plex-pvc"
  config:
    claimName: "plex-pvc"

resources: {}
podAnnotations: {}
proxy:
  enable: false
