---
# Source: sabnzbd/templates/downloads-pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sabnzbd-downloads
  labels:
    name: sabnzbd
    helm.sh/chart: sabnzbd-1.0.0
    app.kubernetes.io/name: sabnzbd
    app.kubernetes.io/instance: sabnzbd
    app.kubernetes.io/version: "arm32v7-latest"
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: local-media-pv
  resources:
    requests:
      storage: "1000Gi"
