---
# Source: sabnzbd/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sabnzbd
  labels:
    name: sabnzbd
    helm.sh/chart: sabnzbd-1.0.0
    app.kubernetes.io/name: sabnzbd
    app.kubernetes.io/instance: sabnzbd
    app.kubernetes.io/version: "arm32v7-latest"
    app.kubernetes.io/managed-by: Helm
