---
# Source: radarr/templates/config-pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: radarr-config
  labels:
    helm.sh/chart: radarr-1.0.0
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: radarr
    app.kubernetes.io/version: "arm32v7-latest"
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - "ReadWriteMany"
  storageClassName: local-media-pv
  resources:
    requests:
      storage: "1Gi"
