---
# Source: radarr/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: radarr
  labels:
    helm.sh/chart: radarr-1.0.0
    app.kubernetes.io/name: radarr
    app.kubernetes.io/instance: radarr
    app.kubernetes.io/version: "arm32v7-latest"
    app.kubernetes.io/managed-by: Helm
