---
# Source: lazylibrarian/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lazylibrarian
  labels:
    helm.sh/chart: lazylibrarian-1.0.0
    app.kubernetes.io/name: lazylibrarian
    app.kubernetes.io/instance: lazylibrarian
    app.kubernetes.io/version: "arm32v7-latest"
    app.kubernetes.io/managed-by: Helm
